<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\my_custom_module\App;

/**
 * Handy wrapper around App::instance().
 *
 * @return Drupal\my_custom_module\App
 *   The App singleton.
 */
function app() : App {
  return App::instance();
}

/**
 * Implements hook_cron().
 */
function my_custom_module_cron() {
  app()->hookCron();
}

/**
 * Implements hook_theme().
 */
function my_custom_module_theme($existing, $type, $theme, $path) {
  return app()->hookTheme($existing, $type, $theme, $path);
}

function my_custom_module_preprocess_node(&$variables) {
  return app()->hookPreprocessNode($variables);
}
