_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_theme: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  conditional_fields: 0
  config: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  geolocation_address: 0
  geolocation_google_maps: 0
  image: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  my_custom_module: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  r4032login: 0
  redirect: 0
  serialization: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  toolbar_visibility: 0
  uli_custom_workflow: 0
  user: 0
  views_ui: 0
  watchdog_watchdog: 0
  webform: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  claro: 0
  stable9: 0
  franchises: 0
profile: standard
