_core:
  default_config_hash: rhZSITSyZWD_Szi-f4ebo9a5Pc92Y7IZAClWzTqQkhM
untranslated_uli_anonymous_message: 'You have successfully logged in.'
untranslated_uli_authenticated_message: 'You are already logged in.'
